Online-discount-card-service/odcs-frontend

- src/features/default-layout/ui/index.tsx
базовая структура для хедера и контента
> feat(default-layout): базовая структура для хедера и контента

- package-lock.json
- package.json
Добавил в зависимости react-hook-form
> build: add dep for react-hook-form

- src/shared/ui/fieldset-mui/index.tsx
- src/shared/ui/form-mui/index.tsx
Добавил базовые компоненты для формы и филдсета на MUI
> feat: add basic form and fieldset comps

- src/shared/ui/Input-mui/index.tsx
- src/stories/input.stories.ts
Отрефакторил инпут, добавил в сторибук примеры как в вайрфреймах
> refactor: refactor mui input comp, add storybook examples

- src/shared/lib/theme.ts
Поправил перепутанные Primary и Secondary цвета в палитре темы
> fix: fix palette colors

- package.json
Удалил неиспользуемые зависимости
> build: delete unnesessary deps

- src/shared/ui/account-button/index.tsx
- src/shared/ui/account-button/style.ts
- src/shared/ui/index.ts
- src/stories/accountButton.stories.ts
Добавила кнопку аккаунта пользователя.
> feat(shared): add account-button

- package-lock.json
- package.json
- src/pages/AddedCard.tsx
- src/stories/addedCard.stories.ts
Страница добавленной карты. Ещё не смотрел как мы будем добавлять штрихкод, поэтому пока просто затычка
> feat: added added-card page

- package-lock.json
- package.json
- src/app/app.tsx
- src/shared/lib/theme.ts
- src/shared/ui/Logo/style.ts
- Добавил библиотеки typeface для шрифтов Roboto (наш основной шрифт) и Nunito (используем в логотипе)
- Добавил шрифт в тему
- Отрефакторил Logo компонент, определил в нем шрифт Nunito
close #55
> feat: add Roboto and Nunito fonts

- src/entities/auth-form/index.tsx
- src/features/auth/sign-in/index.tsx
- src/features/auth/sign-up/index.tsx
- src/widgets/authorization/index.tsx
- src/widgets/header/index.tsx
- src/widgets/header/style.ts
Поправил Header. Изменил кнопку, убрал лишние элементы
close #45
> refactor: refactor header, delete nav buttons, refactor login button

- src/features/carousel/index.ts
- src/features/carousel/ui/index.tsx
- src/features/carousel/ui/style.ts
- src/features/index.ts
- src/shared/mock/img-promo-cards.ts
- src/shared/ui/index.ts
- src/shared/ui/promo-card/index.tsx
- src/shared/ui/promo-card/style.ts
- src/stories/carousel.stories.ts
Добавила карусель, но она пока не крутиться.
Это шесть промо-карт, четыре из них за кадром.
> feat(features): add carousel

- src/widgets/authorization/index.tsx
Добавил Title на вкладку sign-up
> refactor: refactor sign-up screen

- src/entities/auth-form/index.tsx
- src/features/auth/sign-in/index.tsx
Добавил иконки глаза и предупреждения в инпуты форм авторизации
closes #47 closes #48
> refactor: add adornments to auth-form inputs

- tsconfig.json
Поправил tsconfig для импорта статических картинок
closes #112
> fix: fix static image imports

- Dockerfile
> fix: fix dokerfile

- src/widgets/home/index.tsx
>  fix/BUG-149

- .env.development
- .env.production
- src/app/app.tsx
- src/env.d.ts
- src/shared/api/ApiRequests.ts
- src/shared/constants/index.ts
- src/shared/types/index.ts
Добавил типы в Api и getShops в App для дебага
> refactor: add types for Api class

- src/app/app.tsx
- src/app/contexts/cardContext.ts
- src/app/contexts/cardsContext.ts
- src/app/contexts/contexts.tsx
- src/app/contexts/shopListContext.ts
- src/app/contexts/userContext.ts
- src/features/auth/auth-form/index.tsx
- src/features/auth/auth-logic/index.ts
- src/features/auth/index.ts
- src/features/auth/sign-in/index.tsx
- src/features/auth/sign-out/index.tsx
- src/features/auth/sign-up/index.tsx
- src/features/index.ts
- src/features/user/index.ts
- src/shared/api/ApiRequests.ts
- src/shared/types/index.ts
- src/widgets/cards-list/index.tsx
- src/widgets/user-cards/index.tsx
- src/widgets/welcome/index.tsx
Добавил авторизацию — Sign Up и Sign In. Добавил загрузку Shops и User при запуске приложения. Поправил Api. Добавил отображение юзера в Welcome
**Пр еще в работе**
> feat: add authorization. signUp and signIn

- src/features/auth/sign-out/index.tsx
- src/widgets/header/index.tsx
Поправил в Header логику отображения кнопок и добавил в логаут очистку контекстов
> feat: set up Header auth logic, add cleaning contexts on logout

- src/app/app.tsx
- src/app/index.ts
- src/app/protected-home-route/index.tsx
- src/app/protected-route/index.tsx
Добавил защищенные маршруты. Показатель авторизации — наличие данных пользователя в контексте User Context.
closes #186
> feat: add protected routing

- src/app/contexts/cardsContext.ts
- src/app/contexts/contexts.tsx
- src/entities/add-card-form/index.tsx
- src/entities/add-card-form/model/index.ts
- src/entities/card-small/index.tsx
- src/shared/api/ApiRequests.ts
- src/widgets/cards-list/index.tsx
**Фича ещё не готова**
Нужно решить корсовую проблему (как я понимаю, она на стороне сервера), а также посмотреть cardsContext - сейчас в default стейте лежит неправильное значение
> feat: started work on addind new card

- src/stories/components/cardFull.stories.ts
- src/stories/components/editCardForm.stories.ts
- src/stories/widgets/userCardsWidget.stories.ts
> fix: fix stories for build

- src/app/contexts/contexts.tsx
- src/entities/card-small/index.tsx
- src/features/auth/auth-logic/index.ts
- src/features/auth/sign-in/index.tsx
- src/shared/api/ApiRequests.ts
Добавил удаление токена при неуспешной авторизации. Добавил проверку ошибок в fetch. Добавил загрузку карт пользователя при успешном логине
> fix: fix user check on login, add cards update after signin

- package.json
Добавил скрипиты build-dev для билда с использованием .env.development и preview-dev для локального запуска превью билда на порту, который настроен в CORS на бэкенде
> build: add build testing scripts

- src/shared/api/ApiRequests.ts
Убрал ненужный интерфейс, добавил и поправил функцию добавления к url картинок базового url бэкенда
closes #236
> fix: delete unneeded interface, fix handling url prefixing

- src/entities/add-card-form/index.tsx
Поправил логику поля выбора названия магазина в AddCardForm
closes #226
> fix: fix autocomplete field logic in AddCardForm

- src/app/contexts/messageContext.ts
- src/features/info-bar/index.tsx
- src/shared/enums/index.ts
- src/shared/types/index.ts
Переименовала enumes в более информативные  имена.
closes #237
> refactor: rename enum Type and Target

- src/widgets/home/index.tsx
- src/widgets/welcome/index.tsx
> fix: fix paths of images

- src/shared/api/ApiRequests.ts
Поправил апи для отправки запроса на логаут
> fix: signout route to be sent with token

- src/entities/add-card-form/index.tsx
- src/entities/edit-card-form/index.tsx
- src/features/info-bar/index.tsx
Поправил импорты в Edit Card Form, value в Autocomplete в Add Card Form, цвет тостов
> fix: fix after merges

- src/features/cards/SortCards.ts
- src/features/cards/index.ts
- src/features/index.ts
- src/shared/types/index.ts
- src/widgets/cards-list/index.tsx
Добавил сортировку карт в списке карт пользователя по дате добавления и избранности
closes #278
> feat: sorting cards at Cards List

- package-lock.json
- package.json
- src/features/auth/sign-up/index.tsx
- src/shared/ui/input/index.tsx
Добавил библиотеку react-imask, добавил возможность маскирования в компонент Input, настроил маскирование номера телефона в форме регистрации
closes #119
> feat: add masking for inputs

- src/features/auth/index.ts
- src/features/auth/reset-password-form/index.tsx
- src/features/auth/sign-in/index.tsx
- src/features/auth/sign-up/index.tsx
- src/features/back-button/index.tsx
- src/features/back-button/style.ts
- src/shared/api/ApiRequests.ts
- src/widgets/activation/index.tsx
- src/widgets/authorization/index.tsx
- src/widgets/authorization/style.ts
- tsconfig.json
Добавил экран отправки запроса для восстановления пароля. Отрефакторил компоненты авторизации. Отрефакторил экран авторизации по ссылке для активации почты.
closes #282
> feat: add password reset screen

- src/widgets/authorization/index.tsx
Поправил проверку location в Auth. Нельзя было войти по прямому роуту
> fix: fix auth location check

- src/entities/add-card-form/index.tsx
- src/features/add-card-button/index.tsx
Немного переделала userEffect с location.state.shop
- посмотрела у тебя и тоже применила опциональную цепочку и оператор нулевого слияния.
> refactor: change userEffect in add-card-form

- src/app/app.tsx
- src/app/contexts/contexts.tsx
- src/entities/add-card-form/index.tsx
- src/entities/edit-card-form/index.tsx
- src/features/auth/auth-form/index.tsx
- src/features/auth/change-email/index.tsx
- src/features/auth/index.ts
- src/features/auth/reset-password-form/index.tsx
- src/features/auth/set-new-password-form/index.tsx
- src/features/auth/sign-up/index.tsx
- src/features/back-button/style.ts
- src/shared/api/ApiRequests.ts
- src/shared/types/index.ts
- src/widgets/activation/index.tsx
- src/widgets/authorization/index.tsx
- src/widgets/card-widget/index.tsx
- src/widgets/change-email/index.tsx
- src/widgets/change-email/style.ts
- src/widgets/index.ts
- src/widgets/registration-success/index.tsx
- src/widgets/reset-password-request-success/index.tsx
- src/widgets/set-new-password/index.tsx
- src/widgets/set-new-password/style.ts
Вообщем, смена email почти работает, но у меня что-то не доработано с автоматической авторизацией.
Пароль получается менять, если подтвердил почту.
> feat: add possibility to change password and email

- src/features/auth/reset-password-form/index.tsx
> fix: fix number check on reset password request

- src/app/protected-home-route/index.tsx
- src/features/search-chips/index.tsx
- src/widgets/user-cards/index.tsx
- Только группы, доступные юзеру
- При лайке сортировка не слетает
> feat: added cheaps-sorting

- src/widgets/activation/index.tsx
- src/widgets/activation/style.ts
Поправил экран авторизации при активации почты по макету
closes #289
> fix: fix screen according to layout

- src/features/search-chips/index.tsx
- src/shared/assets/selected-chip-icon.svg
- src/shared/ui/chip-button/index.tsx
- src/shared/ui/chip-button/style.css
- src/shared/ui/chip-button/style.ts
> fix: added multichoise to chips with visual

- src/entities/edit-card-form/index.tsx
- src/shared/api/ApiRequests.ts
- src/shared/ui/chip-button/index.tsx
- src/widgets/home/index.tsx
Добавил возможность редактирования категории карты. Категория редактируется только у карт, созданных пользователем. Запрос отправляется только если новая категория отличается от текущей. В этом же коммите починил ошибки TS в Chips Button и Home Widget
closes #386
> feat: edit card category function, fix ts errors in Chip Button

- src/features/auth/change-password-form/index.tsx
- src/features/auth/user-profile-form/index.tsx
- src/widgets/user-profile/index.tsx
- src/widgets/user-profile/style.ts
Поправил экран профиля и запроса смены пароля. Починил установку дефолтного значения номера в форме.
> refactor: refactor User Profile screen, fix form issues

- src/pages/root-layout/index.tsx
- src/widgets/user-cards/index.tsx
- src/widgets/user-cards/styles.ts
Убрал ссылку на Sign Out из User Cards и поправил верстку
> refactor: remove signout from cards, refactor layout

- src/entities/add-card-form/index.tsx
- src/entities/input-password/index.tsx
- src/features/search-chips/index.tsx
- src/features/search-chips/style.ts
- src/shared/ui/input/index.tsx
- src/shared/ui/popup/style.ts
- поправил инпут пароля, починил баг с фокусом, сделал глазик видимым всегда. Убрал из инпутов
отображение иконки ошибки.
- поправил Chips Slider чтобы справа чипс уходил за экран, а слева первый чип останавливался на
правильном отступе. Поправил интервал между чипсами.
- поправил поля для выбора магазина и категории карты
> refactor: refactored password input, chips slider, shop and category fields in add card form

- src/entities/add-card-form/index.tsx
- src/entities/card-share-popup/index.tsx
- src/entities/edit-card-form/index.tsx
- src/shared/validation/index.ts
- src/widgets/card-widget/index.tsx
Поправил поведение инпута shop_group в Add Card и Edit Card. Немного подкорректировал валидацию.
closes #411, closes #417, closes #399
> refactor: refactor shop_group input, fix validation issues

- src/features/liker/index.tsx
Убрал console.log и добавил обработку ошибок в Liker
closes #402
> refactor: add error handling in Liker

- src/features/auth/change-email-form/index.tsx
- src/features/auth/change-password-form/index.tsx
- src/features/auth/delete-user-form/index.tsx
- src/features/auth/reset-password-form/index.tsx
- src/features/auth/set-new-password-form/index.tsx
- src/features/auth/sign-in/index.tsx
- src/features/auth/sign-up/index.tsx
- src/shared/mock/default-cards.ts
- src/stories/components/cardFull.stories.ts
- src/stories/components/editCardForm.stories.ts
Починил проблемы в Stories, и с типами данных в формах. Поправил мок-карты
> fix: fix stories and types issues

- src/app/app.tsx
- src/entities/activate-email-popup/index.tsx
- src/entities/activate-email-popup/style.ts
- src/entities/index.ts
- src/features/auth/user-profile-form/index.tsx
- src/features/auth/user-profile-form/style.ts
- src/features/index.ts
- src/features/reactivate-email/index.tsx
- src/features/reactivate-email/style.ts
- src/shared/api/ApiRequests.ts
- src/shared/types/index.ts
- src/widgets/activation/index.tsx
- src/widgets/index.ts
- src/widgets/reactivation-success/index.tsx
- src/widgets/reactivation-success/styles.ts
- src/widgets/user-profile/index.tsx
Добавил логику для повторного запроса ссылки на активацию почты в профиле пользователя
closes #429
> feat: add logic for email activation from profile

- src/app/contexts/contexts.tsx
- src/features/info-bar/index.tsx
- src/shared/types/index.ts
Поправил вывод тостов, теперь сообщения не появляются повторно
closes #361, closes #339, closes #426, closes #427
> refactor: refactor Snack Bar, fix freezing toasts

- src/features/auth/sign-in/index.tsx
Добавил тост с сообщением о необходимости подтверждить Email после логина
closes #340
> feat: add toast on email not activated after sign in

- src/app/protected-home-route/index.tsx
- src/app/protected-route/index.tsx
- src/entities/add-card-form/index.tsx
- src/entities/edit-card-form/index.tsx
- src/features/auth/auth-form/index.tsx
- src/features/auth/change-password-form/index.tsx
- src/features/auth/delete-user-form/index.tsx
- src/features/auth/reset-password-form/index.tsx
- src/features/auth/set-new-password-form/index.tsx
- src/features/auth/sign-in/index.tsx
- src/features/auth/sign-out/index.tsx
- src/features/auth/sign-up/index.tsx
- src/features/auth/user-profile-form/index.tsx
- src/features/card-share-form/index.tsx
- src/features/reactivate-email/index.tsx
- src/shared/store/useUser.ts
- src/shared/ui/input/index.tsx
- src/shared/validation/index.ts
- src/widgets/activation/index.tsx
- Отрефакторил формы, теперь везде используем управляемые компоненты. Пропали баги с падением лейблов в поля, с дефолтными значениями телефона. 
- Поправил роутинг. Теперь роуты доступны по прямым ссылкам.
closes #465, closes #111
> refactor: refactor forms (inputs to controlled components), add isLoading to protected routes
